---
- name: bootstrap esxi
  hosts: esxi
  gather_facts: false
  remote_user: root
  tasks:
    - name: name 
      raw: uname -a
      register: uname_a 

    - debug:
        var: uname_a

    - name: enable cdp
      raw: esxcli network vswitch standard set --cdp-status=both -v vSwitch0

    - name: generate ssl certificates
      raw: generate-certificates

    - name: set hostname
      raw: "esxcli system hostname set --fqdn={{ ansible_hostname  }}"

#    - name: set dhcp hostname
#      - template: src=dhclient-vmk0.conf.j2 dest=/etc/dhclient-vmk0.conf

    - name: Generate certification
      raw: /bin/generate-certificates

    - name: Enable vSphere MOB
      raw: vim-cmd hostsvc/advopt/update Config.HostAgent.plugins.solo.enableMob bool true
