---
- name: bootstrap esxi
  hosts: esxi
  #  gather_facts: false
  remote_user: root
  tasks:
    - name: name 
      raw: uname -a
      register: uname_a 

    - debug:
        var: uname_a


    - name: set host
      raw: "esxcli system hostname set --host={{ ansible_hostname  }}"

    - name: set fqdn
      raw: "esxcli system hostname set --fqdn={{ ansible_hostname  }}"
     
        # esxcli network vswitch standard list -v vSwitch0
    - name: enable cdp
      raw: esxcli network vswitch standard set --cdp-status=both -v vSwitch0


    - name: generate ssl certificates
      raw: generate-certificates

    - name: Download NUTS upsmon
      get_url:
        url: http://rene.margar.fr/download/1368/
        dest: /tmp/NutClient-ESXi-2.0.0.tar.gz 
        mode: 0440

#    - name: set dhcp hostname
#      - template: src=dhclient-vmk0.conf.j2 dest=/etc/dhclient-vmk0.conf
#
#    - name: Generate certification
#      raw: /bin/generate-certificates
#
#    - name: Enable vSphere MOB
#      raw: vim-cmd hostsvc/advopt/update Config.HostAgent.plugins.solo.enableMob bool true
#
#    - name: Set DNS
#      raw: esxcli network ip dns server add -s {{ name_server }}
