---
- name: stop usbarbitrator
  command: /etc/init.d/usbarbitrator stop

- name: disable usbarbitrator
  command: chkconfig usbarbitrator off

- name: enable the use of USB disks
  command: esxcli system settings advanced set -o /VSAN/AllowUsbDisks -i 1
